name: Update Leaderboard

on:
  pull_request:
    types:
      - closed


jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
       
         
      - name: Update Leaderboard
        env:
          MY_SECRET: ${{ secrets.API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Pass the api_token secret as an environment variable to your script
          python update_leaderboard.py