name: Update Leaderboard

on:
  pull_request:
    types:
      - closed


jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
       
      - name: Use a secret
        env:
          MY_SECRET: ${{ secrets.api_token }}
        run: echo $MY_SECRET
         
      - name: Update Leaderboard
        run: |
          # Pass the api_token secret as an environment variable to your script
          export api_token=$MY_SECRET
          python update_leaderboard.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug Environment
        run: |
          env